title       = "wheretheiss"
baseURL     = "https://wheretheiss-cli.tamnd.com/"
description = "A command line for wheretheiss."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/wheretheiss-cli"
